// <auto-generated />
namespace SportsStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class eligul : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eligul));
        
        string IMigrationMetadata.Id
        {
            get { return "201505241616090_eligul"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
